version: "3"

services:
  ftp-server:
    image: stilliard/pure-ftpd@sha256:1d15f8091b18d399178acc47559b9328c3deecca732d52df96e65303d6a8a966
    container_name: ftp
    hostname: ftp
    environment:
      - PUBLICHOST=0.0.0.0
      - FTP_USER_NAME=username
      - FTP_USER_PASS=password
      - FTP_USER_HOME=/tmp/files/
    ports:
      - 21:21
      - "30000:30000"
    networks:
      - interface
  client-container:
    image: nicoja/client-container
    container_name: client
    hostname: client
    command: python transfer_ftp.py
    environment:
      - FTP_SERVER_ADDRESS=ftp
      - FTP_USER_NAME=username
      - FTP_USER_PASS=password
      - DEBUG=True
    stdin_open: true
    tty: true
    volumes:
      - /tmp/:/tmp/
    networks:
      - interface
    depends_on:
      - ftp-server

networks:
  interface: