version: "3"

services:
  ipfs-node:
    image: nicoja/ipfs-node
    container_name: ipfs
    hostname: ipfs
    command: daemon --offline
    environment:
      # Localhost if running --net=host, or 0.0.0.0 running using Docker networks
      - ADDRESS=127.0.0.1
    volumes:
      - /tmp/:/tmp/
    network_mode: "host"
  ipfs-service:
    image: nicoja/ipfs-service2
    container_name: service
    hostname: service
    environment:
      - BIND_ADDRESS=127.0.0.1
      - BOOTSTRAP_ADDRESS=127.0.0.1
      - DAEMON_ADDRESS=/ip4/127.0.0.1/tcp/5001
      # Omitable
      - BENCHMARK=True
      - OFFLINE_MODE=True
      - CHUNKER=size-262144
    network_mode: "host"
    volumes:
      - /tmp/:/tmp/
  client-container:
    image: nicoja/client-container
    container_name: client
    hostname: client
    command: python ${SCRIPT}
    environment:
      - SERVICE_ADDRESS=http://127.0.0.1:8000
      - FILE_SIZE=${FILE_SIZE}
      - RUN_COUNT=${RUN_COUNT}
      - INTERVAL_SECONDS=${INTERVAL_SECONDS}
    stdin_open: true
    tty: true
    network_mode: "host"
    volumes:
      - /tmp/:/tmp/