version: "3"

services:
  webdav_server:
    image: bytemark/webdav:2.4
    container_name: webdav
    hostname: webdav
    environment:
      - AUTH_TYPE=Digest
      - USERNAME=username
      - PASSWORD=password
    network_mode: "host"